### ISSUE TITLE
Video transform tencrop

### ISSUE THREAD

**Issue by naviocean** [hassony2/videotransforms_pytorch#1]
Hello,
Do you have video transform for tencrop?
Thanks

**Comment by hassony2** [comment]
Hi @naviocean,

Unfortunately I have not implemented it and have no plan of implementing it in the near future !
You might be able to find some inspiration for a solution in the transforms of  [the 3D-ResNets-PyTorch repo](https://github.com/kenshohara/3D-ResNets-PyTorch/blob/94dd85a7a249e4e909864a1a7e201b848867d3c2/spatial_transforms.py)  ?

All the best,

Yana
