### ISSUE TITLE
import error with skimage

### ISSUE THREAD

**Issue by tomginsberg** [hassony2/videotransforms_pytorch#11]
Hi, great package works well.

When I call a video transform I get the error
`AttributeError: module 'skimage' has no attribute 'transform'`

I see the same issue [here](https://github.com/scikit-image/scikit-image/issues/4241)

The simple fix is to replace 
```
import skimage
skimage.transform.(whatever)
```
with 
```
import skimage.transform
skimage.transform.(whatever)
```
As mentioned in the linked issue, scikit-image uses "lazy importing", so you have to explicitly import submodules.

**Comment by hassony2** [comment]
This should be fixed now, thank you very much !

Best,

Yana
